all:
	g++ -std=c++17 -O3 arithmetic_encode.cpp -o q1
	g++ -std=c++17 -O3 bwtsearch.cpp -o bwtsearch
	g++ -std=c++17 -O3 bwt-encode.cpp -o bwtencode
	g++ -std=c++17 -O3 bwtdecode.cpp -o bwtdecode
	g++ -std=c++17 -O3 lzw-encode.cpp -o lzwencode
	g++ -std=c++17 -O3 lzw-decode.cpp -o lzwdecode
	g++ -std=c++17 -O3 acdecode.cpp -o acdecode
clean:
	rm -f q1
	rm -f bwtsearch
	rm -f bwtencode
	rm -f bwtdecode